name: Security Audit

on:
  schedule:
    # Run security audit weekly
    - cron: '0 2 * * 1'
  push:
    paths:
      - '**/package*.json'
      - '.github/workflows/security.yml'

jobs:
  audit:
    name: Dependency Security Audit
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run npm audit
        run: npm audit --audit-level moderate
        
      - name: Run Snyk security test
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high --all-projects
          
      - name: Check for known vulnerabilities in Docker base images
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'image'
          image-ref: 'node:18-alpine'
          format: 'sarif'
          output: 'docker-trivy-results.sarif'
          
      - name: Upload Docker scan results
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: 'docker-trivy-results.sarif'